# Generated by Django 5.1.7 on 2025-03-07 02:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPayment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('transaction', models.CharField(max_length=50, verbose_name='Transaction')),
                ('quantity', models.IntegerField(default=1)),
                ('product_price_payed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product price at the time of payment')),
                ('payed_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Payed')),
                ('payment_successful', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_payments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'verbose_name': 'Product Payment',
                'verbose_name_plural': 'Product Payments',
                'db_table': 'product_payment',
            },
        ),
    ]
