# Generated by Django 5.1.7 on 2025-03-13 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_productcategory_image'),
        ('payments', '0002_alter_productpayment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='number_of_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producttype'),
        ),
    ]
