# Generated by Django 5.1.6 on 2025-03-06 01:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerCart',
            fields=[
                ('cart_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
                ('products', models.ManyToManyField(to='products.product')),
            ],
            options={
                'verbose_name': 'Buyer Cart',
                'db_table': 'buyer_cart',
            },
        ),
        migrations.CreateModel(
            name='BuyerSavedProduct',
            fields=[
                ('saved_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
                ('products', models.ManyToManyField(to='products.product')),
            ],
            options={
                'verbose_name': 'Buyer Saved Product',
                'verbose_name_plural': 'Buyer Saved Products',
                'db_table': 'buyer_saved_products',
            },
        ),
    ]
