# Generated by Django 5.1.7 on 2025-03-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_id_pic',
            field=models.ImageField(blank=True, null=True, upload_to='student_id_pic'),
        ),
    ]
