# Generated by Django 5.1.7 on 2025-03-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_student_id_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_id_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Student IDs'),
        ),
    ]
