# Generated by Django 5.1.7 on 2025-03-18 06:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_student_id_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_images'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='student_id',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='student_id_pic'),
        ),
    ]
